apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  image: julepai/crunchy-pg-custom
  postgresVersion: 17

  config:
    parameters:
      shared_preload_libraries: "timescaledb"

  users:
    - name: hippo
      databases:
        - zoo
    - name: postgres
      databases:
        - postgres
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        storageClassName: auto-ebs-sc
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: auto-ebs-sc
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi
